export const ROUTE_NAMES = {
  DASHBOARD: 'dashboard',
  AUTH_LOGIN: 'auth.login',
  PEMBANDING_LIST: 'pembanding.list',
  PEMBANDING_CREATE: 'pembanding.create',
  PEMBANDING_DUPLICATE_REVIEW: 'pembanding.duplicate-review',
  PEMBANDING_DETAIL: 'pembanding.detail',
  PEMBANDING_EDIT: 'pembanding.edit',
  MODERATION_INDEX: 'moderation.index',
  MASTER_DATA_INDEX: 'master-data.index',
  WILAYAH_INDEX: 'wilayah.index',
  USER_INDEX: 'user.index',
  ACCESS_CONTROL_INDEX: 'access-control.index',
  CONTRIBUTOR_INVITATION_INDEX: 'contributor-invitation.index',
  CONTRIBUTOR_REGISTER: 'contributor.register',
  IMPORT_INDEX: 'import.index',
  IMPORT_DETAIL: 'import.detail',
  INTEGRATIONS: 'integrations.index',
  SETTINGS: 'settings',
  ACTIVITY_LOGS: 'activity-log.index',
  SEARCH: 'search',
  PROFILE: 'profile',
  NOTIFICATIONS: 'notifications.index',
  BACKUP: 'backup.index',
  FOUNDATION: 'foundation',
  DESIGN_SYSTEM: 'design-system',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'not-found',
} as const

export type RouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES]
